import { shell, app, BrowserWindow, ipcMain, session, webContents } from 'electron';
import fs from 'fs';
import path from 'path'
import {exec} from 'child_process';
import SecurityKeyDaemon, { SecurtyKeyVerificationResult } from '@/daemons/securityKey';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const securityKeyDaemon = new SecurityKeyDaemon()

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const debug = !app.isPackaged

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 1300,
    height: 850,
    minWidth: 800,
    minHeight: 600,
    titleBarStyle: 'hidden',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    }
  });

  const toLoginPage = () => {
    if (!debug) {
      // mainWindow.loadFile(MAIN_WINDOW_WEBPACK_ENTRY);
      mainWindow.loadFile('index.html');
    } else {
      mainWindow.loadURL('http://localhost:3001/');
    }
  }

  var modelID:number = null

  toLoginPage()
  if (debug) {
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  }

  ipcMain.handle('dev:is-debug-mode',      async () => debug)
  ipcMain.handle('dev:toggle-dev-tools',   async () => { mainWindow.webContents.openDevTools({ mode: 'detach' }) })
  ipcMain.handle('dev:load-extension',     async (event, path) => await session.defaultSession.loadExtension(path))

  ipcMain.handle('nav:to-login-page',      toLoginPage)

  ipcMain.handle('global:open-external',   async (event, url) => { await shell.openExternal(url) })
  ipcMain.handle("window:minimize",        async () => { mainWindow.minimize() })
  ipcMain.handle("window:toggle-maximize", async () => { mainWindow.isMaximized() ? mainWindow.unmaximize() : mainWindow.maximize() })
  ipcMain.handle("window:close",           async () => {
    mainWindow.close()
    app.quit()
  })

  ipcMain.handle("user:login", async () => {
    console.log("Congratulations! You have successfully logged in.")
  })

  ipcMain.handle("ready:login-page",async () => {
    console.log('content loaded')
    securityKeyDaemon.refresh()
  })

  ipcMain.handle("local-model:start",async () => {
    if (modelID !== null){
      return
    }
    securityKeyDaemon.emit('run_local_model')
    const model_path = path.join(securityKeyDaemon.getLastVerifiedResult().path,'assets','PrivataLocalModel','dist','model.exe')
    const child = exec(model_path)
    modelID = child.pid
  }),

  ipcMain.handle("local-model:terminate",async () => {
    if (modelID === null){
      return
    }
    process.kill(modelID, 'SIGINT')
  })


  securityKeyDaemon.on('verification_changed', result => {
    console.log(result)
    mainWindow.webContents.send('verification_changed', result)
  })
  
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
