name: build-artifacts
run-name: Build Artifacts
on: [push]
jobs:
  build-mac-artifacts:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v